### ISSUE TITLE
Why does it say the mutation survives?

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/cypress-mutation-example#3]
Stryker says that this mutation survives the tests

```diff
-   ReactDOM.render(<App />, document.getElementById('root'))
+   ReactDOM.render(<App />, document.getElementById(""))
```

In

```
#0. [Survived] StringLiteral
/Users/gleb/git/cypress-mutation-example/src/index.js:4:49
-   ReactDOM.render(<App />, document.getElementById('root'))
+   ReactDOM.render(<App />, document.getElementById(""))

Ran all tests for this mutant.
Ran 1.00 tests per mutant on average.
```

**Comment by bahmutov** [comment]
Blocked from finding the reason by Stryker removing the temp folder after the failed test run https://github.com/stryker-mutator/stryker/issues/2681

**Comment by simondel** [comment]
Hi! What happens to your unit tests when you manually make this change to your code?

**Comment by bahmutov** [comment]
Manually mutating the src/index.js the same way
```js
ReactDOM.render(<App />, document.getElementById(''))
```
and running `npm run ci` fails

<img width="1273" alt="Screen Shot 2021-01-05 at 8 14 20 AM" src="https://user-images.githubusercontent.com/2212006/103650451-0a032400-4f2e-11eb-8d56-c78b0b443143.png">

and the process exits with code 1

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypress-mutation-example@1.0.0 cy:run: `cypress run`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cypress-mutation-example@1.0.0 cy:run script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gleb/.npm/_logs/2021-01-05T13_14_04_861Z-debug.log
Error: Command failed with exit code 1: npm run cy:run
    at makeError (/Users/gleb/git/cypress-mutation-example/node_modules/start-server-and-test/node_modules/execa/lib/error.js:56:11)
    at handlePromise (/Users/gleb/git/cypress-mutation-example/node_modules/start-server-and-test/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:94:5) {
  command: 'npm run cy:run',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypress-mutation-example@1.0.0 ci: `start-test 3000 cy:run`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cypress-mutation-example@1.0.0 ci script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gleb/.npm/_logs/2021-01-05T13_14_04_942Z-debug.log
~/git/cypress-mutation-example on main*
$ echo $?
1
```

Also I don't understand why I do not see the above output from the Cypress test runner when running `npm run test:mutations` command

**Comment by simondel** [comment]
I'm not familiar with the way Cypress works unfortunately, but the `npm run ci` command keeps a process open and I don't see any logging of it running any tests. It almost looks like that command actually starts the server with the user's application.

What did you do to get to the logging you posted in the initial issue message?

PS: 
Stryker currently does not have specific support for Cypress. This will cause it to run your specified command for **every** mutation. In Cypress's case it will require your code to be recompiled and a browser to be started. If you want to run concurrently, the browsers will have to automatically decide on a new (unused) port to run on. All of this combined will cause the (already slow) mutation testing process to be incredibly slow because it will most likely take multiple seconds for the test run to start and for the test run to complete. If you do this thousands of times, it will start to add up.

For some test runners such as Karma, Mocha and Jest we have specific programmatic integration so we can keep the test process alive in between test runs, eliminating overhead and (in some cases) allow us to specifically run the tests that covered the code that has now been mutated. This allowed Stryker to run in a fraction of the time required.

Even if someone were to add a specific programmatic integration for Cypress and Stryker, I believe it will still be a lot slower than other integrations as Cypress is (as far as I'm aware) meant for UI tests. It's very good and optimized at doing that, but still. It's testing with significantly larger units of works than a unit test would.
